logging:
  level: INFO
  loggers:
    org.videoMaker: DEBUG

mongo:
  seeds:
  - host: localhost
    port: 27017
  database: videoMaker
  credentials:
    userName: mongoAdmin
    password: lightfly33

#consumerKey:
#consumerKeySecret:
#accessKey:
#accessKeySecret:
