logging:
  level: INFO
  loggers:
    org.videoMaker: DEBUG

mongo:
  seeds:
  - host: localhost
    port: 27017
  database: videoMaker
  credentials:
    userName: "josh_sure"
    password: "easyasdoremiabc123uandme"

consumerKey: "yAadiPN8pOodJors6n9dZla96"
consumerKeySecret: "ejdU0yalC8tfbfk0R00Sbau2HENquRErOl25W7Kzbi5lfDquDp"
accessKey: "951789582-Tv3Rj5GfnH9v2ganaMYRFJn8tmzDcmrTBj5NZB63"
accessKeySecret: "NJvIItM8ZrKgcluyKVczNzPt0hUVnHcQOFtHqLgynBkZA"

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: lightfly33
  url: jdbc:mysql://localhost/videoMaker

#    userName:
#    password:

#consumerKey:
#consumerKeySecret:
#accessKey:
#accessKeySecret: